service: ruby-template

frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  logRetentionInDays: 7
  deploymentBucket:
    name: serverless-deployment
package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.idea/**'
    - '!node_modules/**'
    - '!package.json'
    - '!yarn.lock'
    - '!README*'
    - '!Dockerfile'
    - '!docker-compose.yml'
    - vendor/bundle/**
    - Gemfile
    - Gemfile.lock

plugins:
  - serverless-prune-plugin

functions:
  hello:
    handler: handler.hello
    description: remind OWNRAPP Backlog tickets
    timeout: 300
#    environment:
#      DUMMY_STRING: ${ssm:/ruby/template/dummy-string}
#      DUMMY_SECURE_STRING: ${ssm:/ruby/template/dummy-secure-string~true}

custom:
  prune:
    automatic: true
    number: 3
